spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/whatCode
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  ssl:
    key-store: keystore.p12
    key-store-password: whatcode
    key-store-type: PKCS12
    keyAlias: tomcat